//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormClase2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name dni from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUILValidator", ReplyAction="*")]
        WindowsFormClase2.ServiceReference1.CUILValidatorResponse CUILValidator(WindowsFormClase2.ServiceReference1.CUILValidatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUILValidator", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormClase2.ServiceReference1.CUILValidatorResponse> CUILValidatorAsync(WindowsFormClase2.ServiceReference1.CUILValidatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CUILValidatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CUILValidator", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormClase2.ServiceReference1.CUILValidatorRequestBody Body;
        
        public CUILValidatorRequest() {
        }
        
        public CUILValidatorRequest(WindowsFormClase2.ServiceReference1.CUILValidatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CUILValidatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int verificador;
        
        public CUILValidatorRequestBody() {
        }
        
        public CUILValidatorRequestBody(int tipo, string dni, int verificador) {
            this.tipo = tipo;
            this.dni = dni;
            this.verificador = verificador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CUILValidatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CUILValidatorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormClase2.ServiceReference1.CUILValidatorResponseBody Body;
        
        public CUILValidatorResponse() {
        }
        
        public CUILValidatorResponse(WindowsFormClase2.ServiceReference1.CUILValidatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CUILValidatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CUILValidatorResult;
        
        public CUILValidatorResponseBody() {
        }
        
        public CUILValidatorResponseBody(bool CUILValidatorResult) {
            this.CUILValidatorResult = CUILValidatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormClase2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormClase2.ServiceReference1.WebService1Soap>, WindowsFormClase2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormClase2.ServiceReference1.CUILValidatorResponse WindowsFormClase2.ServiceReference1.WebService1Soap.CUILValidator(WindowsFormClase2.ServiceReference1.CUILValidatorRequest request) {
            return base.Channel.CUILValidator(request);
        }
        
        public bool CUILValidator(int tipo, string dni, int verificador) {
            WindowsFormClase2.ServiceReference1.CUILValidatorRequest inValue = new WindowsFormClase2.ServiceReference1.CUILValidatorRequest();
            inValue.Body = new WindowsFormClase2.ServiceReference1.CUILValidatorRequestBody();
            inValue.Body.tipo = tipo;
            inValue.Body.dni = dni;
            inValue.Body.verificador = verificador;
            WindowsFormClase2.ServiceReference1.CUILValidatorResponse retVal = ((WindowsFormClase2.ServiceReference1.WebService1Soap)(this)).CUILValidator(inValue);
            return retVal.Body.CUILValidatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormClase2.ServiceReference1.CUILValidatorResponse> WindowsFormClase2.ServiceReference1.WebService1Soap.CUILValidatorAsync(WindowsFormClase2.ServiceReference1.CUILValidatorRequest request) {
            return base.Channel.CUILValidatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormClase2.ServiceReference1.CUILValidatorResponse> CUILValidatorAsync(int tipo, string dni, int verificador) {
            WindowsFormClase2.ServiceReference1.CUILValidatorRequest inValue = new WindowsFormClase2.ServiceReference1.CUILValidatorRequest();
            inValue.Body = new WindowsFormClase2.ServiceReference1.CUILValidatorRequestBody();
            inValue.Body.tipo = tipo;
            inValue.Body.dni = dni;
            inValue.Body.verificador = verificador;
            return ((WindowsFormClase2.ServiceReference1.WebService1Soap)(this)).CUILValidatorAsync(inValue);
        }
    }
}
